services:
  - type: web
    name: ai-learning-assistant
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Add your key manually
