services:
  - type: web
    name: ai-learning-assistant
    env: docker
    plan: free
    region: singapore
    dockerfilePath: backend/Dockerfile
    rootDir: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ai-learning-assistant-ag67.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1ftb9ngi27c73e8f2qg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ai_learning_db_nnkz
      - key: DB_USERNAME
        value: ai_learning_db_nnkz_user
      - key: DB_PASSWORD
        value: fsP5ekoPwNI5MxOunqp4coa4ZM1p9FBU
