services:
  - type: web
    name: ai-learning-assistant
    env: docker
    plan: free
    region: singapore
    rootDir: backend                 # This tells Render to treat /backend as the working dir
    dockerfilePath: Dockerfile      # Dockerfile is inside /backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Add manually in Render Dashboard
